@startuml
node database{
  file file[
    <b>File</b>
    ===
    path of the file
    file type
    ---
    tags
    family
  ]
  file soup[
    <b>Wordbox</b>
    ===
    tags
    ---
    families
  ]
  database table[
  | files | t::tag | f::family | ... |
  | type::path | 0    | 0     | ... |
  | type::path | 1    | 0     | ... |
  | type::path | 0    | 1     | ... |
  | type::path | 1    | 1     | ... |
  ]
}
agent Note[
 <b>Note</b>
 Tags and families are the same.
 The only difference is that
 family is the main tag. Because
 the topic structure in school

 Families and tags should be
 separated by commas
]
@enduml
